### ISSUE TITLE
UI probleme mit IE

### ISSUE THREAD

**Issue by irisgasser** [Mattia98/IschStreik#5]
language, description und hamburger funktionieren nicht

**Comment by Mattia98** [comment]
Usability auf IE verbessert. Zukünftige Verbesserungen kommen.

**Comment by Mattia98** [comment]
IE wird nicht mehr weiterhin unterstützt. Eine Meldung muss eingebaut werden.

**Comment by Mattia98** [comment]
Closed with a739129988356ab0368ab652476b6de7873cb6fd
